[workspace]
resolver = "3"
members = [
    "core_graph",
    "core_rules",
    "model_enc",
    "model_dec",
    "retriever",
    "trainer",
    "datasets",
    "evalbench",
    "cli",
]

[workspace.dependencies]
approx = "0.5"
rstest = "0.18"
