[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
core_graph = { path = "../core_graph" }
core_rules = { path = "../core_rules" }
evalbench = { path = "../evalbench" }
pprof = { version = "0.13", features = ["flamegraph"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
trainer = { path = "../trainer" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

[dev-dependencies]
tempfile = "3.10"
