[package]
name = "core_rules"
version = "0.1.0"
edition = "2024"

[dependencies]
core_graph = { path = "../core_graph" }
retriever = { path = "../retriever" }
tracing = "0.1"

[dev-dependencies]
approx = { workspace = true }
